name: Deploy FastAPI to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Updated to v4 to fix the Node warning
      - name: Checkout code
        uses: actions/checkout@v4

      # Updated to v5 to fix the Node warning
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Package application
        run: |
          # Download libraries into a temporary folder named "package"
          pip install -t package -r requirements.txt
          
          # Go into the folder and zip all the libraries
          cd package
          zip -r9 ../function.zip .
          
          # Go back out and add your main.py file to the zip
          cd ..
          zip -g function.zip main.py

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: mapthatjob-backend
          zip_file: function.zip
